[build]
  command = "NODE_ENV=production npm start"
  publish = "distribution"

# [[headers]]
#   for = "/*"

#   [headers.values]
#     content-security-policy = "default-src rss.wtf; block-all-mixed-content; style-src 'unsafe-inline' rss.wtf; img-src rss.wtf *.rss.wtf; media-src *; frame-src *; font-src data:; connect-src rss.wtf *.rss.wtf https://*.userbase.com wss://*.userbase.com"

#     for = "/*"
#       feature-policy = "autoplay 'none'; camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'"
#       link = '''
#       </offline.js>; rel=prefetch; as=serviceworker; crossorigin=anonymous,
#       <https://services.rss.wtf>; rel=preconnect'''
#       referrer-policy = "no-referrer"
#       x-content-type-options = "nosniff"
#       x-frame-options = "DENY"
#       x-xss-protection = "1; mode=block"
